ITEM.name = "Батарея темной энергии"
ITEM.uniqueID = "bullets_dominator"
ITEM.model = "models/Items/car_battery01.mdl"
ITEM.description = "Одноразовая батарея, хранящая огромные объемы темной энергии."
ITEM.maxStack = 90
ITEM.defaultStack = 90
ITEM.width = 2
ITEM.height = 2
ITEM.rarity = 2
