ITEM.name = "Картофель"
ITEM.description = "Картофель, выращенный вручную."
ITEM.model = "models/foodnhouseholditems/potato.mdl"
ITEM.cost = 8
ITEM.width = 1
ITEM.height = 1
ITEM.dUses = 2
ITEM.dHunger = 9
ITEM.dThirst = -2
ITEM.rarity = 2
